name: z/OS ML Project Board
type: project
description: Project board for z/OS Machine Learning Transaction Analyzer

columns:
  - name: To do
    type: todo
    description: Tasks that need to be done
    
  - name: In progress
    type: in_progress
    description: Tasks currently being worked on
    
  - name: Review
    type: review
    description: Tasks that need review
    
  - name: Done
    type: done
    description: Completed tasks

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
    
  - name: enhancement
    color: a2eeef
    description: New feature or request
    
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
    
  - name: performance
    color: 0e8a16
    description: Performance related changes
    
  - name: security
    color: e99695
    description: Security related changes
    
  - name: z/OS
    color: fbca04
    description: z/OS specific changes
