name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
    
    - name: Run Bandit
      run: |
        bandit -r . -f sarif -o bandit-results.sarif || true
    
    - name: Upload Bandit scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: bandit-results.sarif
