name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Security vulnerabilities scan
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor

    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r . -f json -o bandit-results.json || true

    - name: Upload Bandit scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: bandit-results.json
